name: Node.js CI

on:
  push:
    branches: [ chore/ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint step
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/yarn.lock
      - run: yarn install
        working-directory: frontend